[build]
  publish = "."

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 200

# If you use client-side routing (like SPA fallback), add this:
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
