[[redirects]]
  from = "/term"
  to = "/term.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[functions]
  directory = "netlify/functions"

[build]
  functions = "netlify/functions"
  publish = "."

